sample RAML for Experience Layer API

defining 5 endpoints for instance:

. AddLocation
/locations POST

. UpdateLocation
/locations/{locationId} PATCH

. Remove Location
/locations/{locationId} PATCH

. Find Location
/locations/{locationId} GET

. LocationList
/locations GET